### ISSUE TITLE
When will the code will be available?

### ISSUE THREAD

**Issue by Prof-pengyin** [whyjay/memoryGAN#1]
Thanks for your hard work, When will the code will be available?

**Comment by whyjay** [comment]
Hi, the code and model parameter will be available in a couple of weeks. 
Thank you.

**Comment by Prof-pengyin** [comment]
Great!

Peng Yin / Max
Research Scholar
Robotics Institute, Carnegie Mellon University

Website: https://sites.google.com/andrew.cmu.edu/maxtom/home
Tel: (+1) 412-209-9837
Email: pyin2@andrew.cmu.edu / hitmaxtom@gmail.com
